syntax = "proto3";
package document;

import "common.proto";

service DocumentService {
  rpc GetDocument (GetDocumentRequest) returns (DocumentResponse);
  rpc ListDocuments (ListDocumentsRequest) returns (ListDocumentsResponse);
}

message GetDocumentRequest {
  string document_id = 1;
}

message DocumentResponse {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string file_type = 4;
  int32 char_count = 5;
  int32 word_count = 6;
  string status = 7;
  string created_at = 8;
}

message ListDocumentsRequest {
  string user_id = 1;
  common.Pagination pagination = 2;
}

message ListDocumentsResponse {
  repeated DocumentResponse documents = 1;
  common.PaginatedMeta meta = 2;
}
